Document: libsrt
Title: Debian libsrt Manual
Author: <insert document author here>
Abstract: This manual describes what libsrt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libsrt/libsrt.sgml.gz

Format: postscript
Files: /usr/share/doc/libsrt/libsrt.ps.gz

Format: text
Files: /usr/share/doc/libsrt/libsrt.text.gz

Format: HTML
Index: /usr/share/doc/libsrt/html/index.html
Files: /usr/share/doc/libsrt/html/*.html
